### ISSUE TITLE
Housekeeping 

### ISSUE THREAD

**Issue by Albadylic** [fac-17/My-Body-Back#31]
Some things to decide on:

- [x] Code of Conduct #45
- [x] Timetable / Schedule #46 
- [x] Naming conventions for: #52 
   - Classes & IDs (all-lowercase-hyphenated)
   - Branches (Feature/all-lowercase Fix/redesign-this)
- [x]  Issues
   - Have a description
   - Assign to yourself
   - Relate / Fix in commit
   - Scrum reviews & labels
- [x] File Structure (DevOps) #47
- [x] Dependencies (DevOps) #49
- [x]  React Router (DevOps) #48
- [x] Code Cov (QA) #50
- [x] Style Guide (UX/UI) #51

**Comment by Albadylic** [comment]
All discussed and issues related.
