### ISSUE TITLE
Appointment Page

### ISSUE THREAD

**Issue by Albadylic** [fac-17/My-Body-Back#63]
Should be rendered by clicking right hand menu button. 

Should include:
- [x] Header
- [x] Menu

When the user swipes left or right, the content changes based on state.

On one:
Should render:
- [x]  Title - "My appointment"
- [x]  Text about thinking about a smear test

On two:
Should render:
- [x]  Title - "Preparation"
- [ ] Box you can tap that shows you different tips on tap. (Replaced by #132)

On three:
Should render:
- [x]  Title - "Your appointment"
- [x] Text - introduction to appointment card

On four:
Should render:
- [x]  Title - "Your appointment"
- [ ] Appointment card (editable) (Replaced by #150)
- [ ]  Tap to edit text
- [x]  Button to download

On five:
Should render:
- [x]  Title - "After appointment"
- [ ] Video - after your appointment (Replaced by #133 )
- [x] Link to Notes of Love

Requires:
- [x] Styling
- [ ] Testing
